FROM python:3.7-alpine

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# upgrade pip
RUN pip install --upgrade pip

# install dependencies
COPY ./requirements.txt .
RUN pip --no-cache-dir --no-deps  -r requirements.txt

# create directory for the app user
RUN mkdir -p /home/app

# create the appropriate directories
ENV HOME=/home/app
ENV APP_HOME=/home/app/web
RUN mkdir $APP_HOME

WORKDIR $APP_HOME

COPY . $APP_HOME

RUN chmod u+x makemigrations.sh

RUN ./makemigrations.sh

EXPOSE 8080/tcp



